### ISSUE TITLE
connect ETIMEDOUT

### ISSUE THREAD

**Issue by PRO-2684** [ramensoftware/windhawk#145] opened 2024-01-15 07:46 UTC
```
request to https://mods.windhawk.net/catalog.json failed, reason: connect ETIMEDOUT 172.67.216.218:443
```

![image](https://github.com/ramensoftware/windhawk/assets/54608551/77c4696a-b179-4516-a80a-f87290f50f9d)

Windhawk notifies me that a certain mod has an update, but when I visit the mods page, it won't load due to connection timeout. However, that reported URL is accessible if I visit it in my browser.

**Comment by m417z** [comment] 2024-01-16 08:04
Are you using a proxy? Perhaps it's the same issue as https://github.com/ramensoftware/windhawk/issues/134
Unfortunately, VSCode, which is used by Windhawk, has limited proxy support: https://github.com/microsoft/vscode/issues/12588

**Comment by PRO-2684** [comment] 2024-01-16 09:15
> Are you using a proxy? Perhaps it's the same issue as #134 Unfortunately, VSCode, which is used by Windhawk, has limited proxy support: [microsoft/vscode#12588](https://github.com/microsoft/vscode/issues/12588)

Yes, but unfortunately disabling the proxy yields the same result. (I can still visit that `catalog.json` on my browser)

**Comment by m417z** [comment] 2024-01-16 18:29
I'm not sure. Perhaps the browser still has the proxy server configured somehow? As an additional check, you can open cmd and try the following command:
```
curl https://mods.windhawk.net/catalog.json
```

**Comment by PRO-2684** [comment] 2024-01-20 13:05
Curious. It now works fine. I don't know why, but it seems that rebooting solves the problem.

**Comment by m417z** [comment] 2024-01-20 13:56
OK, closing as a duplicate of https://github.com/ramensoftware/windhawk/issues/134.

**Closed by m417z** 2024-01-20 13:56 UTC
Labels: bug

**Comment by iyyyyy0963** [comment] 2024-10-26 08:51
e

**Comment by iyyyyy0963** [comment] 2024-10-26 08:53
request to https://mods.windhawk,net/catalog.json failed
reason: read ECONNRESET

**Comment by m417z** [comment] 2024-10-26 08:56
@iyyyyy0963 does it work when you open it in the browser?
