### ISSUE TITLE
Add a setting to hide that pop-up in the bottom right corner.

### ISSUE THREAD

**Issue by N0VA-The-Git-User** [ramensoftware/windhawk#208] opened 2024-06-19 19:58 UTC
I get it means there is something wrong, but I don't want to see it.

![image](https://github.com/ramensoftware/windhawk/assets/145279552/4b29e184-522f-4e0b-b2bf-9fa86ebc163b)

**Comment by win98se** [comment] 2024-06-22 02:56
> It means there is something wrong

There is nothing wrong. The mods will only work after the initialization of the mods are complete.
Usually this dialog only appears for a longer time after a cumulative update installation (usually released on the second Tuesday of every month), because the mods depend on symbols to work properly.

**Comment by N0VA-The-Git-User** [comment] 2024-06-23 02:54
Oh, well they are appearing a LOT more often than that. Many every day.

**Comment by m417z** [comment] 2024-06-25 03:06
I'd like to fix this issue, or at least understand why it hangs, in which case I'll be able to detect this state and hide the dialog. As you said, it indicates that something's wrong, it shouldn't just hang initializing.

If that happens a lot for you, can you [create a dump with Task Manager](https://www.barco.com/en/support/knowledge-base/2669-creating-a-dump-file-using-task-manager-for-troubleshooting-app-crashes-and-hangs) for that process and post it here (or [email it to me](https://ramensoftware.com/contact))?

Also, does this happen with this specific process? You can exclude it, either in Aerexplorer in the mod's advanced tab, or globally in Windhawk's advanced settings.

Closing as a duplicate of this issue: https://github.com/ramensoftware/windhawk/issues/153.

**Closed by m417z** 2024-06-25 03:06 UTC
Labels: enhancement
