### ISSUE TITLE
Feature request: Windhawk browser, support mouse back-button

### ISSUE THREAD

**Issue by ThisIsABug** [ramensoftware/windhawk#359] opened 2024-12-16 09:16 UTC
Would be great if we could use the Back-Button on our mouse to go from an extension-details-page back to the explore-list of windhawk-mods.

**Comment by m417z** [comment] 2024-12-16 11:07
Thanks for the suggestion. Closing as a duplicate of https://github.com/ramensoftware/windhawk/issues/221.

**Closed by m417z** 2024-12-16 11:07 UTC
