### ISSUE TITLE
Windhawk Setup is already running

### ISSUE THREAD

**Issue by webian** [ramensoftware/windhawk#127] opened 2023-11-07 09:00 UTC
Hello,
when I run windhawk_setup.exe v1.4, even after restarting Windows, a popup appears with text "Windhawk Setup is already running". Is there something I can do to upgrade?

**Comment by m417z** [comment] 2023-11-07 22:15
That's an issue I haven't encountered before. If you check in Task Manager before running the setup, how many processes of `windhawk_setup.exe` do you see? After running the setup and getting the message, while it's open, how many processes do you see?

**Comment by webian** [comment] 2023-11-08 07:07
Sure, it was the first thing I checked. I see only the one that I launch. Also after a Windows restart, same problem.

**Comment by m417z** [comment] 2023-11-08 14:35
I think I understand why that happens. Can you run the setup as administrator? Does that help?

**Comment by m417z** [comment] 2023-11-09 00:22
I believe that the issue is fixed in Windhawk v1.4.1. If not, please let me know.

**Closed by m417z** 2023-11-09 00:22 UTC
Labels: bug
