### ISSUE TITLE
Windows 11 won't automatically sleep with Windhawk running

### ISSUE THREAD

**Issue by duckduckdog** [ramensoftware/windhawk#51] opened 2023-03-15 01:20 UTC
First let me say I love the app.

Windows 11 (latest preview) won't automatically sleep with Windhawk running. It took me awhile to find the culprit as powercfg /requests was clean & Windows would sleep manually just fine.

This started around when I updated to 1.1 beta (at which point I also installed "Shrink Address Bar Height" with no other mods running)

let me know if you want any logs or to isolate the cause further.

**Comment by m417z** [comment] 2023-03-15 11:22
I couldn't reproduce the problem. Are you sure that Windhawk prevents the system from sleeping? Does it happen when Windhawk is open, or also when it's just running in the background? Are you using the standard or the portable version?

**Comment by m417z** [comment] 2023-04-15 19:36
Eventually I was able to reproduce the issue, it should be fixed in version 1.3.1.

**Closed by m417z** 2023-04-15 19:36 UTC

**Comment by duckduckdog** [comment] 2023-07-01 23:27
I'm sorry to have posted with such limited information and bailed, I guess it slipped my mind & I didn't see any notifications from github.
