### ISSUE TITLE
Complete Backup (all at once)

### ISSUE THREAD

**Issue by dbareis** [ramensoftware/windhawk#367] opened 2024-12-30 05:40 UTC
Ideally I'd like auto-backups, but a manual backup with a single button that backups windhawk configuration (including installed mods) as well as each installed mod's configuration would be great.  Ideally I would be able to use this backup to reset the settings of individual mods also and not just restore a previous complete configuration.

Either way can I do this by backing up files or registry now?  If so where is the data?

**Comment by m417z** [comment] 2024-12-30 06:16
Thanks for the feedback, it's planned. Closing as a duplicate of https://github.com/ramensoftware/windhawk/issues/195.

For registry and file paths for manual export, please see https://github.com/ramensoftware/windhawk/discussions/155#discussioncomment-8495683.

**Closed by m417z** 2024-12-30 06:16 UTC
Labels: enhancement
