### ISSUE TITLE
v1.4 breaks the start menus search function

### ISSUE THREAD

**Issue by mertzi** [ramensoftware/windhawk#129] opened 2023-11-08 17:47 UTC
Hi! 
I just updated to 1.4 and the start menu became all wonky, clicking start (or using the win key) and starting to type afterwards to search didn't work. Could easily reproduce it by exiting windhawk and then reopen. Rolled back to 1.3.1 and the issue disappeared. Very odd.
The only mod I use now is "Taskbar height and icon size".

**Comment by m417z** [comment] 2023-11-09 00:21
A duplicate of https://github.com/ramensoftware/windhawk/issues/126. Fixed in Windhawk v1.4.1.

**Closed by m417z** 2023-11-09 00:21 UTC
Labels: bug
