### ISSUE TITLE
Windhawk break VirtualBox

### ISSUE THREAD

**Issue by Smiley0227** [ramensoftware/windhawk#48] opened 2023-03-03 03:24 UTC
This is new as of the last few days. Last time I used VirtualBox without issue with Windhawk loaded was February 26th, so four days ago.

When Windhawk is loaded and I try to start a VM (any of the three VMs I have setup) in VirtualBox I get the error message, "suphardenedwinverifyprocess failed with verr_sup_vp_replace_virtual_memory_failed (rc=-5637)".

I researched the error message and came upon METHOD A at [this solution](https://stackoverflow.com/questions/50992120/why-cant-i-start-the-virtual-machine-i-just-built-using-vitrualbox/75243719#75243719).

I exited Windhawk and retried and was able to launch my VMs.

As a troubleshooting step, I loaded Windhawk again but disabled all mods and tried again. The error message popped up again.

Is there anything else I should try for troubleshooting?

Windhawk v1.1 beta
VirtualBox Version 7.0.6 r155176 (Qt5.15.2)
![VirtualBox w-Windhawk error message](https://user-images.githubusercontent.com/24441944/222624037-c76c034e-0ed2-4e11-aa3b-dd530182cbc8.png)

**Comment by m417z** [comment] 2023-03-03 07:54
A duplicate of https://github.com/ramensoftware/windhawk/issues/25 and https://github.com/ramensoftware/windhawk/issues/39

From the issue above:
> this failure is due to unsigned code injection being detected in the VM host process, so VirtualBox refuses to start the VM

The best solution is to exclude VirtualBox in the advanced settings of Windhawk. Let me know if you need help with that.

**Comment by Smiley0227** [comment] 2023-03-05 16:22
Thanks, it worked!

**Closed** 2023-03-05 16:22 UTC
