### ISSUE TITLE
Conflict with Virtualbox

### ISSUE THREAD

**Issue by mick88** [ramensoftware/windhawk#87] opened 2023-06-13 15:52 UTC
I have been having issues booting up a VM using a VirtualMachine. When looking at VBoxHardening.log, I found this:

```
700.51ec:  *00007ffa85c20000-00007ffa85c20fff 0x0002/0x0080 0x1000000  \Device\HarddiskVolume3\Program Files\Windhawk\Engine\1.3.1\64\windhawk.dll
700.51ec: supHardNtVpScanVirtualMemory: Ignoring unknown mem at 00007ffa85c20000 LB 0x1000 (base 00007ffa85c20000) - 'windhawk.dll'
700.51ec:   00007ffa85c21000-00007ffa85c68fff 0x0020/0x0080 0x1000000  \Device\HarddiskVolume3\Program Files\Windhawk\Engine\1.3.1\64\windhawk.dll
700.51ec: supHardNtVpScanVirtualMemory: Ignoring unknown mem at 00007ffa85c21000 LB 0x48000 (base 00007ffa85c20000) - 'windhawk.dll'
700.51ec:   00007ffa85c69000-00007ffa85cf0fff 0x0002/0x0080 0x1000000  \Device\HarddiskVolume3\Program Files\Windhawk\Engine\1.3.1\64\windhawk.dll
700.51ec: supHardNtVpScanVirtualMemory: Ignoring unknown mem at 00007ffa85c69000 LB 0x88000 (base 00007ffa85c20000) - 'windhawk.dll'
700.51ec:   00007ffa85cf1000-00007ffa85cf1fff 0x0004/0x0080 0x1000000  \Device\HarddiskVolume3\Program Files\Windhawk\Engine\1.3.1\64\windhawk.dll
700.51ec: supHardNtVpScanVirtualMemory: Ignoring unknown mem at 00007ffa85cf1000 LB 0x1000 (base 00007ffa85c20000) - 'windhawk.dll'
700.51ec:   00007ffa85cf2000-00007ffa85cf2fff 0x0008/0x0080 0x1000000  \Device\HarddiskVolume3\Program Files\Windhawk\Engine\1.3.1\64\windhawk.dll
700.51ec: supHardNtVpScanVirtualMemory: Ignoring unknown mem at 00007ffa85cf2000 LB 0x1000 (base 00007ffa85c20000) - 'windhawk.dll'
700.51ec:   00007ffa85cf3000-00007ffa85cf4fff 0x0004/0x0080 0x1000000  \Device\HarddiskVolume3\Program Files\Windhawk\Engine\1.3.1\64\windhawk.dll
700.51ec: supHardNtVpScanVirtualMemory: Ignoring unknown mem at 00007ffa85cf3000 LB 0x2000 (base 00007ffa85c20000) - 'windhawk.dll'
700.51ec:   00007ffa85cf5000-00007ffa85cfcfff 0x0002/0x0080 0x1000000  \Device\HarddiskVolume3\Program Files\Windhawk\Engine\1.3.1\64\windhawk.dll
700.51ec: supHardNtVpScanVirtualMemory: Ignoring unknown mem at 00007ffa85cf5000 LB 0x8000 (base 00007ffa85c20000) - 'windhawk.dll'
```

after turning off windhawk, Virtualbox is working again.

I also found that someone else reported a similar problem already on Oracle forums:
https://forums.virtualbox.org/viewtopic.php?f=6&t=109353

**Comment by m417z** [comment] 2023-06-13 20:43
A duplicate of https://github.com/ramensoftware/windhawk/issues/25

From the issue above:

> this failure is due to unsigned code injection being detected in the VM host process, so VirtualBox refuses to start the VM

The best solution is to exclude VirtualBox in the advanced settings of Windhawk. Let me know if you need help with that.

**Closed by m417z** 2023-06-13 20:43 UTC
