### ISSUE TITLE
Import/Export Mod Settings

### ISSUE THREAD

**Issue by coderguy-21** [ramensoftware/windhawk#365] opened 2024-12-27 22:00 UTC
Any chance of getting some kind of import/export for settings?

I need to set up a couple more computers and I would like to clone my current setup, but I have a number of mods installed with multiple settings for a bunch of them, and its going to be a PITA to do all that manually

**Comment by m417z** [comment] 2024-12-28 10:04
Thanks for the feedback, it's planned. Closing as a duplicate of https://github.com/ramensoftware/windhawk/issues/195.

**Closed by m417z** 2024-12-28 10:04 UTC
Labels: enhancement
