### ISSUE TITLE
Allow Multiple Instances or Add Backwards Compatibility

### ISSUE THREAD

**Issue by legacy1477** [ramensoftware/windhawk#139] opened 2023-12-29 11:45 UTC
An issue already showed up with some scripts breaking in newer versions of Windhawk.

An easy solution would be to allow multiple versions to run at the same time.
Or add a line in the source code indicating Windhawk should emulate an older version.

For example:

```
// ==WindhawkMod==
// @id              new-mod
// @name            Your Awesome Mod
// @description     The best mod ever that does great things
// @version         0.1
// @author          You
// @compatibility         1.3.1 
```

**Comment by m417z** [comment] 2023-12-29 11:49
That's not something that can be easily done. Ideally, such breakage should be very rare, and shouldn't affect mods in the official repository. Ideally it would be a good idea to verify that all mods compile before releasing a new version, but I didn't have the time to implement such a check yet.

What breakage did you encounter? Please post the code of the mod if possible.

**Comment by m417z** [comment] 2023-12-29 22:03
I tried to compile this mod with the latest Windhawk version and it worked. Perhaps the problem was caused by copying Windhawk header files around. Once you start doing those kinds of things, nothing is guaranteed to work.

I'm closing this issue since there seems to be no problem, and since I'm not planning to implement the "old version mode" suggestion.

If you encounter mods that worked with an older version but no longer compile with the latest, unmodified Windhawk, please let me know.

**Comment by m417z** [comment] 2023-12-30 07:33
I'm not using a classic theme so I'm not sure how to test it. @aubymori any idea? I don't see a reason for it to behave differently in v1. 3.1 and 1v.4.1.

**Comment by aubymori** [comment] 2023-12-30 08:11
Ah, I remember I found what causes this but I forgot to do anything about it. I'll push an update shortly.

**Comment by m417z** [comment] 2023-12-30 08:20
Thanks @aubymori

@legacy1477 from the updated description:

> # IMPORTANT: READ!
> Windhawk and this mod need to inject into `conhost.exe` for this mod to work properly.
> Please navigate to Windhawk's Settings, Advanced settings, More advanced settings, and
> make sure that `conhost.exe` is in the Process inclusion list.

conhost.exe is marked as a system process, and Windhawk v1.4.1 doesn’t inject code into it by default. It’s tricky to find the right balance between safety and functionality, I’ll keep gathering user feedback and will adjust Windhawk accordingly.

**Closed by m417z** 2023-12-30 08:20 UTC
Labels: enhancement
