### ISSUE TITLE
Mouse sensitive controls

### ISSUE THREAD

**Issue by ninjazan420** [ramensoftware/windhawk#354] opened 2024-12-12 12:07 UTC
Hey, 

I would like to recommend a function to recognize mouse inputs to navigate troughout the program.
Mouses do have back and forth buttons nowadays, so it would make it easier for the user to navigate, due the fact that currently, if you look into a mod, you have to scroll all the way back to the top to hit the (very small) back button to get back to the last menu. 
It would be easier, if you could use your mouse buttons for this :)

Thanks and have a good one!

**Comment by m417z** [comment] 2024-12-12 13:01
Thanks for the suggestion. Closing as a duplicate of https://github.com/ramensoftware/windhawk/issues/221.

**Closed by m417z** 2024-12-12 13:01 UTC
Labels: enhancement
